command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8080"

env:
  - name: DATABRICKS_HOST
    value: https://fe-vm-vdm-serverless-mf35v2.cloud.databricks.com
  - name: LAKEBASE_INSTANCE_NAME
    value: vibe-coding-demo
  - name: LAKEBASE_DB_NAME
    value: vibe_coding

